docker:
  image: barto92/kubemon
  tag: 1.0.30

# Should we run an initContainer that enables core tcp connection setting tweaks
enableTcpTweaks: false

config:
  # What port should the server listen on
  port: 8080

  # What should the prometheus metrics be prefixed with
  metricsPrefix: kconmon

  # These are nodes where you do not wish to run the agent
  nodeAntiAffinity:
    - key: airflow
      value: true

  # This is the well known label on a node which identifies the zone
  failureDomainLabel: failure-domain.beta.kubernetes.io/zone

  # TCP test configuration
  tcp:
    interval: 5000
    timeout: 1000

  # UDP test configuration
  udp:
    interval: 5000
    # This is a per-packet timeout
    timeout: 250
    packets: 5

  dns:
    interval: 5000
    hosts:
      - www.google.com
      - kubernetes.default.svc.cluster.local
  
  icmp:
    interval: 5000
    count: 2
    timeout: 5
    hosts:
      - www.telekom.de
      - www.google.com
      - 8.8.4.4
  custom_tcp:
    interval: 5000
    timeout: 1000
    hosts:
      - www.telekom.de
      - www.google.de

resources:
  agent:
    # This will scale with the number of nodes in your cluster at loosely 1m per node
    # The minimum value is 25m
    cpu: 70m
    memory: 45Mi
